#!/usr/local/bin/perl

use strict;
use warnings;
use Benchmark;
use v5.18;

my $t0 = new Benchmark;
my @primes = (2);
my $result = 2;
for(3..1999999) {
        if($_ % 2 != 0 && isprime($_) == $_) {
                push @primes, $_;
                $result += $_;
        }
}
say $result;

my $t1 = new Benchmark;
my $td = timediff($t1, $t0);
say "the code took : ", timestr($td);

sub isprime {
        my $number = shift;
        for(@primes) {
                return 0 if($number % $_ == 0);
                return $number if($_**2 > $number);
        }
}





