#!/usr/local/bin/perl

use strict;
use warnings;

my ($sum, $first, $second) = (0, 0, 1);

while($second <= 4000000) {
   $sum += $second if($second % 2 == 0); 
   ($first, $second) = ($second, $first + $second);
}

print $sum."\n";
