#!/usr/local/bin/perl

use strict;
use warnings;

sub ispalindrome {
    my ($number) = @_;
    my $partial = 0;
    my $tempnumber = $number;

    until($tempnumber == 0) { 
        $partial = ($partial * 10) + ($tempnumber % 10); 
        $tempnumber = int $tempnumber / 10;
    }

    return 1 if($number == $partial);
    return 0;
}


sub lastestpalindrome {
    my $result = 0;
    my $num3 = 0;
    foreach(900..999) { 
        foreach my $i (900..999) {  
            $num3 = $_ * $i;
            $result = $num3 if(ispalindrome($num3) and $result < $num3); 
        }
    } 

    return $result;
}
print lastestpalindrome()."\n";



