#!/usr/local/bin/perl

use strict;
use warnings;
use v5.18;

my ($a, $b, $c) = (0, 0, 0);
my $result = 0;
my $s = 1000;
for my $a (1..333){
        for my $b (1..500) {
                $c = 1000 - $a - $b;
                if($a**2 + $b**2 == $c**2) {
                        $result = $a * $b * $c;
                        last;
                }
        }
        if($result) {
                last;
        } 
}

print $result;
