#!/usr/bin/perl

use strict;
use warnings;


open GRID, "<", "problem11_file.txt" || die "open error $!";

# 줄 단위를 2차원 배열로 만들기 
my @array = map([split], <GRID>);
close GRID;

my $greatest_sum = 0;

# 오른쪽으로 4개씩
for my $x_pos (0..16)
{
	for my $y_pos (0..19)
	{
		my $first = $array[$x_pos][$y_pos];
		my $second = $array[$x_pos+1][$y_pos];
		my $third = $array[$x_pos+2][$y_pos];
		my $forth = $array[$x_pos+3][$y_pos];
		my $sum = $first * $second * $third * $forth;
		$greatest_sum = $sum if($greatest_sum < $sum);
	}
}

#아래로 4개씩
for my $x_pos (0..19)
{
	for my $y_pos (0..16)
	{
		my $first = $array[$x_pos][$y_pos];
		my $second = $array[$x_pos][$y_pos+1];
		my $third = $array[$x_pos][$y_pos+2];
		my $forth = $array[$x_pos][$y_pos+3];
		my $sum = $first * $second * $third * $forth;
		$greatest_sum = $sum if($greatest_sum < $sum);
	}
}

# 오른쪽으로 대각선
for my $x_pos (0..16)
{
	for my $y_pos (0..16)
	{
		my $first = $array[$x_pos][$y_pos];
		my $second = $array[$x_pos+1][$y_pos+1];
		my $third = $array[$x_pos+2][$y_pos+2];
		my $forth = $array[$x_pos+3][$y_pos+3];
		my $sum = $first * $second * $third * $forth;
		$greatest_sum = $sum if($greatest_sum < $sum);
	}
}


# 왼쪽으로 대각선
for my $x_pos (0..16)
{
	for my $y_pos (0..16)
	{
		my $first = $array[$x_pos+3][$y_pos];
		my $second = $array[$x_pos+2][$y_pos+1];
		my $third = $array[$x_pos+1][$y_pos+2];
		my $forth = $array[$x_pos][$y_pos+3];
		my $sum = $first * $second * $third * $forth;
		$greatest_sum = $sum if($greatest_sum < $sum);
	}
}
print "$greatest_sum\n";
