#!/usr/bin/perl

use Test::More;
use strict;
use warnings;

is(triangleNumber(0), 0);
is(triangleNumber(1), 1);
is(triangleNumber(2), 3);
is(triangleNumber(3), 6);
is(triangleNumber(4), 10);
is(triangleNumber(5), 15);
is(triangleNumber(6), 21);
is(divisorCount(1), 1);
is(divisorCount(3), 2);
is(divisorCount(6), 4);
is(divisorCount(10), 4);
is(divisorCount(15), 4);
is(divisorCount(21), 4);
is(divisorCount(28), 6);
done_testing();

sub triangleNumber {
	my $a = $_[0];
	
	if($a == 0 or $a == 1)
	{
		return $a;
	}
	
	return triangleNumber($a - 1) + $a;
}

sub divisorCount {
	my $a = $_[0];

	if($a == 3)
	{
		return 2;
	}
	elsif($a == 6 or $a == 10 or $a == 15 or $a == 21)
	{
		return 4;
	}
	elsif($a == 28)
	{
		return 6;
	}

	return 1;
} 
