#!/usr/local/bin/perl

use strict;
use warnings;
my $i = 1;
while(1) {

    if($i % 16 == 0 and $i % 9 == 0 and $i % 5 == 0
            and $i % 7 == 0 and $i % 11 == 0 and $i % 13 == 0
            and $i % 15 == 0 and $i % 17 == 0 and $i % 19 == 0) {
        print $i;
        last;
    } 

    $i++;
}
